version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: wedding_postgres
    restart: always
    environment:
      POSTGRES_USER: wedding_admin
      POSTGRES_PASSWORD: wedding_password
      POSTGRES_DB: wedding_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
