-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('WEDDING', 'ENGAGEMENT', 'HENNA', 'BIRTHDAY', 'GRADUATION', 'BABY_SHOWER', 'PROMISE', 'CORPORATE', 'PARTY', 'OTHER');

-- CreateEnum
CREATE TYPE "SubjectType" AS ENUM ('COUPLE', 'PERSON', 'ORGANIZATION');

-- AlterTable
ALTER TABLE "DownloadLink" ADD COLUMN IF NOT EXISTS "tokenEncrypted" TEXT;

-- AlterTable
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "eventType" "EventType" NOT NULL DEFAULT 'WEDDING',
ADD COLUMN IF NOT EXISTS "subjectType" "SubjectType" NOT NULL DEFAULT 'COUPLE',
ADD COLUMN IF NOT EXISTS "hostName" TEXT,
ADD COLUMN IF NOT EXISTS "instagramUsername" TEXT,
ALTER COLUMN "brideName" DROP NOT NULL,
ALTER COLUMN "groomName" DROP NOT NULL,
ALTER COLUMN "maxStorageBytes" SET DATA TYPE BIGINT;
